### ISSUE TITLE
newly created AuditoryFrontEndDepKS.getSignalBlock() produces an error

### ISSUE THREAD

**Issue by ivo--t** [TWOEARS/blackboard-system#13]
follow-up on closed #3 .
@ningma97 : "I just notice when I request multi-stream signals such as "time" signals, the newly created AuditoryFrontEndDepKS.getSignalBlock() produces an error. I added a not-so-elegant fix for now. Perhaps Ivo could have a look at this, please."

**Comment by hagenw** [comment]
@ningma97 could you please post a short code example in order to reproduce this bug and provide a link to the commit/changes you did in order to fix it?

**Comment by ningma97** [comment]
if you request a time signal in DnnLocationKS()

```
requests{3}.name = 'time';
requests{3}.params = param;
```

and then in execute() do
`sig = obj.getNextSignalBlock( 3, obj.blockSize, obj.blockSize, false );`
you will get the error, which is related to the fact that 'signalStream' in getSignalBlock() is a 2x1 cell array rather than an object in this case.

What I did is just to check if signalStream is a cell array and do things differently, which is not very elegant.

https://github.com/TWOEARS/blackboard-system/commit/69b06c0538afeabe56b8a3edd413770ab128198b#diff-95f6cc79ce0fa39d05181f9634dec42c

**Comment by ivo--t** [comment]
Cleaned solution.
